using System.Text;
using System.Text.Json;

namespace MassiveDotNet.CodeGen;

/// <summary>Emits the generated half of the REST client.</summary>
internal sealed class Emitter(Spec spec, Map map)
{
    private const string Header = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     Generated by tools/MassiveDotNet.CodeGen from specs/openapi.json and
        //     specs/endpoints.map.json. Manual edits are overwritten on the next run.
        //     Hand-written members belong in the matching partial type instead.
        // </auto-generated>
        //------------------------------------------------------------------------------

        // The .g.cs suffix marks these files auto-generated, which suppresses the project's
        // nullable context, so it is re-enabled explicitly here.
        #nullable enable
        """;

    private const int UriBufferLength = 256;

    public Dictionary<string, string> Emit()
    {
        Dictionary<string, string> files = new(StringComparer.Ordinal);

        foreach (MapModel model in map.Models)
        {
            files[Path.Combine("Models", $"{model.Name}.g.cs")] = EmitModel(model);
        }

        files["Envelopes.g.cs"] = EmitEnvelopes();

        foreach (MapGroup group in map.Groups)
        {
            files[$"{group.Name}Group.g.cs"] = EmitGroup(group);
        }

        files["MassiveRestJsonContext.g.cs"] = EmitJsonContext();

        return files;
    }

    private string EmitModel(MapModel model)
    {
        SpecOperation operation = spec.Operation(model.SchemaOperationId);
        JsonElement schema = Spec.Navigate(Spec.SuccessSchema(operation), model.SchemaPointer);

        // Order by the map's declaration so related fields stay together (OHLCV rather than
        // the alphabetical order the OpenAPI document happens to store them in).
        List<string> declared = [.. model.Properties.Keys];
        List<SpecProperty> properties = [.. Spec.Properties(schema)
            .OrderBy(p => declared.IndexOf(p.Name) is var i and >= 0 ? i : int.MaxValue)];

        CodeWriter writer = new();
        writer.Line(Header);
        writer.Line();
        writer.Line("using System.Text.Json.Serialization;");
        writer.Line();
        writer.Line("namespace MassiveDotNet.Rest.Models;");
        writer.Line();

        writer.Doc("summary", model.Summary, preserveMarkup: true);
        writer.Doc("remarks", model.Remarks, preserveMarkup: true);

        string declaration = model.Kind == "struct"
            ? $"public readonly partial record struct {model.Name}"
            : $"public sealed partial record {model.Name}";

        using (writer.Block(declaration))
        {
            bool first = true;

            foreach (SpecProperty property in properties)
            {
                map.Models.First(m => m.Name == model.Name)
                    .Properties.TryGetValue(property.Name, out MapProperty? mapped);

                if (!first)
                {
                    writer.Line();
                }

                first = false;

                string name = mapped?.Name ?? Naming.Pascal(property.Name);
                string type = mapped?.Type ?? DefaultPropertyType(property);

                writer.Doc("summary", mapped?.Summary ?? Prose.Clean(property.Description));
                writer.Line($"[JsonPropertyName(\"{property.Name}\")]");
                writer.Line($"public {type} {name} {{ get; init; }}");
            }
        }

        return writer.ToString();
    }

    private string EmitEnvelopes()
    {
        bool anyPaginated = map.Endpoints.Any(e => Spec.IsPaginated(spec.Operation(e.OperationId)));

        CodeWriter writer = new();
        writer.Line(Header);
        writer.Line();
        writer.Line("using System.Text.Json.Serialization;");

        // Emitted conditionally: an unused using fails the build under EnforceCodeStyleInBuild.
        if (anyPaginated)
        {
            writer.Line("using MassiveDotNet.Http;");
        }

        writer.Line("using MassiveDotNet.Rest.Models;");
        writer.Line();
        writer.Line("namespace MassiveDotNet.Rest.Serialization;");

        foreach (MapEndpoint endpoint in map.Endpoints)
        {
            SpecOperation operation = spec.Operation(endpoint.OperationId);
            List<SpecProperty> properties = Spec.Properties(Spec.SuccessSchema(operation));
            bool paginated = Spec.IsPaginated(operation);

            writer.Line();
            writer.Doc("summary", $"The response envelope returned by {operation.Path}.");

            string declaration = paginated
                ? $"internal sealed class {EnvelopeName(endpoint)} : IPagedEnvelope<{endpoint.Result.Model}>"
                : $"internal sealed class {EnvelopeName(endpoint)}";

            using (writer.Block(declaration))
            {
                bool first = true;

                foreach (SpecProperty property in properties)
                {
                    if (!first)
                    {
                        writer.Line();
                    }

                    first = false;

                    string type = property.Name == endpoint.Result.Property
                        ? $"{endpoint.Result.Model}[]?"
                        : NullableEnvelopeType(property);

                    writer.Doc("summary", Prose.Clean(property.Description));
                    writer.Line($"[JsonPropertyName(\"{property.Name}\")]");
                    writer.Line($"public {type} {Naming.Pascal(property.Name)} {{ get; init; }}");
                }

                // The interface names the results property `Results`. When the endpoint's result
                // property maps to some other name, satisfy it explicitly rather than renaming
                // the public property away from the wire shape.
                string resultsProperty = Naming.Pascal(endpoint.Result.Property);

                if (paginated && resultsProperty != "Results")
                {
                    writer.Line();
                    writer.Line(
                        $"{endpoint.Result.Model}[]? IPagedEnvelope<{endpoint.Result.Model}>.Results => {resultsProperty};");
                }
            }
        }

        return writer.ToString();
    }

    private string EmitGroup(MapGroup group)
    {
        List<MapEndpoint> endpoints = [.. map.Endpoints.Where(e => e.Group == group.Name)];

        CodeWriter writer = new();
        writer.Line(Header);
        writer.Line();
        writer.Line("using MassiveDotNet.Http;");
        writer.Line("using MassiveDotNet.Rest.Models;");
        writer.Line("using MassiveDotNet.Rest.Serialization;");
        writer.Line();
        writer.Line("namespace MassiveDotNet.Rest;");
        writer.Line();

        using (writer.Block($"public readonly partial struct {group.Name}Group"))
        {
            bool first = true;

            foreach (MapEndpoint endpoint in endpoints)
            {
                if (!first)
                {
                    writer.Line();
                }

                first = false;
                EmitEndpoint(writer, endpoint);
            }
        }

        return writer.ToString();
    }

    private void EmitEndpoint(CodeWriter writer, MapEndpoint endpoint)
    {
        SpecOperation operation = spec.Operation(endpoint.OperationId);
        List<SpecParameter> parameters = spec.Parameters(operation);
        bool paginated = Spec.IsPaginated(operation);

        List<Argument> arguments = [.. parameters
            .Select(p => Argument.Create(p, endpoint.Parameters.GetValueOrDefault(p.Name)))
            .OrderByDescending(a => a.Required)];

        string model = endpoint.Result.Model;
        string returnType = paginated ? $"MassivePage<{model}>" : $"{model}[]";
        string callArguments = string.Join(", ", arguments.Select(a => a.Identifier));
        // Nullable because Prose.Clean returns null for blank prose; Doc skips blank content.
        string? summary = endpoint.Summary ?? Prose.Clean(Summary(operation));
        bool preserve = endpoint.Summary is not null;

        if (paginated)
        {
            // The two entry points share an endpoint but not a shape, so the enumerating one names
            // its own nature rather than repeating the summary verbatim: identical summaries are
            // indistinguishable in IntelliSense, where remarks are not shown.
            writer.Doc(
                "summary",
                AppendClause(summary, "enumerating every page as a single lazy sequence."),
                preserveMarkup: preserve);

            string remarks =
                "Walks every page, requesting the next only once the previous one has been consumed. "
                + $"Use <see cref=\"{endpoint.Method}Async\"/> to retrieve a single page instead.";

            // Emitted only where the endpoint declares the parameter, since not every paginated
            // operation has one. Exists is order-independent, so rule 6 holds.
            if (arguments.Exists(a => a.Identifier == "limit"))
            {
                remarks += " <paramref name=\"limit\"/> sizes each page rather than the traversal, so "
                    + "lowering it issues more requests rather than returning fewer items; bound the "
                    + "sequence with <c>Take</c> instead.";
            }

            // Added to, never replaced: the map carries what the spec cannot, so dropping its
            // remarks here would lose prose that no regeneration could recover.
            if (endpoint.Remarks is { } authored)
            {
                remarks = $"{remarks} {authored}";
            }

            writer.Doc("remarks", remarks, preserveMarkup: true);

            EmitParameterDocs(writer, arguments, "A token to cancel the traversal.");
            writer.Doc(
                "returns",
                $"Every <c>{endpoint.Result.Property}</c> item across every page.",
                preserveMarkup: true);
            writer.Doc("exception", "The server responded with an error status.", "cref=\"MassiveApiException\"");

            List<string> enumerateSignature = Signature(
                $"public IAsyncEnumerable<{model}> {Naming.Enumerate(endpoint.Method)}Async",
                [.. arguments.Select(a => a.Declaration), "CancellationToken cancellationToken = default"]);

            using (writer.Block(enumerateSignature))
            {
                EmitGuards(writer, arguments);
                writer.Line($"string requestUri = Build{endpoint.Method}Uri({callArguments});");
                writer.Line($"return _transport.EnumerateAsync<{EnvelopeName(endpoint)}, {model}>(");
                writer.Line($"    requestUri, MassiveRestJsonContext.Default.{EnvelopeName(endpoint)}, cancellationToken);");
            }

            writer.Line();
        }

        writer.Doc("summary", summary, preserveMarkup: preserve);
        writer.Doc("remarks", endpoint.Remarks, preserveMarkup: true);

        EmitParameterDocs(writer, arguments, "A token to cancel the request.");

        writer.Doc(
            "returns",
            paginated
                ? $"A single page of <c>{endpoint.Result.Property}</c>, reporting whether more exist."
                : $"The <c>{endpoint.Result.Property}</c> array from the response, empty when the server returned none.",
            preserveMarkup: true);
        writer.Doc("exception", "The server responded with an error status.", "cref=\"MassiveApiException\"");

        List<string> signature = Signature(
            $"public Task<{returnType}> {endpoint.Method}Async",
            [.. arguments.Select(a => a.Declaration), "CancellationToken cancellationToken = default"]);

        using (writer.Block(signature))
        {
            EmitGuards(writer, arguments);
            writer.Line($"string requestUri = Build{endpoint.Method}Uri({callArguments});");
            writer.Line($"return Send{endpoint.Method}Async(requestUri, cancellationToken);");
        }

        writer.Line();

        // The URI builder is a ref struct, so it cannot live inside an async method.
        // Composition therefore happens in a separate synchronous method.
        List<string> builderSignature = Signature(
            $"private static string Build{endpoint.Method}Uri",
            [.. arguments.Select(a => a.RequiredDeclaration)]);

        using (writer.Block(builderSignature))
        {
            writer.Line($"RequestUriBuilder builder = new(stackalloc char[{UriBufferLength}]);");
            writer.Line();

            EmitPath(writer, operation.Path, arguments);

            foreach (Argument argument in arguments.Where(a => a.In == "query"))
            {
                writer.Line($"builder.AppendQuery(\"{argument.WireName}\", {argument.QueryExpression});");
            }

            writer.Line();
            writer.Line("return builder.ToUriString();");
        }

        writer.Line();

        using (writer.Block($"private async Task<{returnType}> Send{endpoint.Method}Async(string requestUri, CancellationToken cancellationToken)"))
        {
            writer.Line($"{EnvelopeName(endpoint)}? response = await _transport");
            writer.Line($"    .GetAsync(requestUri, MassiveRestJsonContext.Default.{EnvelopeName(endpoint)}, cancellationToken)");
            writer.Line("    .ConfigureAwait(false);");
            writer.Line();

            if (paginated)
            {
                writer.Line($"return new MassivePage<{model}>(");
                writer.Line($"    response?.{Naming.Pascal(endpoint.Result.Property)},");
                writer.Line("    response?.NextUrl is not null,");
                writer.Line("    response?.RequestId);");
            }
            else
            {
                writer.Line($"return response?.{Naming.Pascal(endpoint.Result.Property)} ?? [];");
            }
        }
    }

    private static void EmitGuards(CodeWriter writer, List<Argument> arguments)
    {
        foreach (Argument argument in arguments.Where(a => a is { Required: true, CSharpType: "string" }))
        {
            writer.Line($"ArgumentException.ThrowIfNullOrWhiteSpace({argument.Identifier});");
        }
    }

    private static void EmitParameterDocs(CodeWriter writer, List<Argument> arguments, string cancellationDescription)
    {
        foreach (Argument argument in arguments)
        {
            writer.Doc("param", argument.Description, $"name=\"{argument.Identifier}\"");
        }

        writer.Doc("param", cancellationDescription, "name=\"cancellationToken\"");
    }

    private static void EmitPath(CodeWriter writer, string path, List<Argument> arguments)
    {
        StringBuilder literal = new();
        int index = 0;

        while (index < path.Length)
        {
            if (path[index] != '{')
            {
                literal.Append(path[index++]);
                continue;
            }

            int close = path.IndexOf('}', index);
            string name = path[(index + 1)..close];
            index = close + 1;

            if (literal.Length > 0)
            {
                writer.Line($"builder.AppendPathLiteral(\"{literal}\");");
                literal.Clear();
            }

            Argument argument = arguments.First(a => a.WireName == name);
            writer.Line($"builder.{argument.PathAppendMethod}({argument.PathExpression});");
        }

        if (literal.Length > 0)
        {
            writer.Line($"builder.AppendPathLiteral(\"{literal}\");");
        }

        writer.Line();
    }

    private string EmitJsonContext()
    {
        CodeWriter writer = new();
        writer.Line(Header);
        writer.Line();
        writer.Line("using System.Text.Json.Serialization;");
        writer.Line();
        writer.Line("namespace MassiveDotNet.Rest.Serialization;");
        writer.Line();
        writer.Doc("summary", "Source-generated serialization metadata for every REST response envelope. Using a context rather than reflection keeps the SDK Native AOT compatible.");

        foreach (MapEndpoint endpoint in map.Endpoints)
        {
            writer.Line($"[JsonSerializable(typeof({EnvelopeName(endpoint)}))]");
        }

        writer.Line("internal sealed partial class MassiveRestJsonContext : JsonSerializerContext;");

        return writer.ToString();
    }

    /// <summary>Wraps a parameter list one-per-line so long signatures stay readable.</summary>
    private static List<string> Signature(string prefix, IReadOnlyList<string> parameters)
    {
        List<string> lines = [$"{prefix}("];

        for (int i = 0; i < parameters.Count; i++)
        {
            string separator = i == parameters.Count - 1 ? ")" : ",";
            lines.Add($"    {parameters[i]}{separator}");
        }

        return lines;
    }

    private static string EnvelopeName(MapEndpoint endpoint) => $"{endpoint.OperationId}Response";

    private static string Summary(SpecOperation operation) =>
        operation.Operation.TryGetProperty("summary", out JsonElement summary)
            ? summary.GetString() ?? operation.OperationId
            : operation.OperationId;

    /// <summary>
    /// Appends a clause to a sentence so the result reads as one sentence, whether or not the
    /// source prose already ended in terminal punctuation.
    /// </summary>
    private static string? AppendClause(string? sentence, string clause) =>
        string.IsNullOrWhiteSpace(sentence)
            ? null
            : $"{sentence.TrimEnd().TrimEnd('.', '!', '?')}, {clause}";

    private static string DefaultPropertyType(SpecProperty property)
    {
        string type = TypeBinding.FromSchema(property.Schema);
        return property.Required || type == "string" ? Nullable(type, property.Required) : $"{type}?";
    }

    private static string NullableEnvelopeType(SpecProperty property)
    {
        string type = TypeBinding.FromSchema(property.Schema);
        return type == "string" ? "string?" : $"{type}?";
    }

    private static string Nullable(string type, bool required) =>
        required ? type : $"{type}?";
}
