using System.Text;
using System.Text.Json;

namespace MassiveDotNet.CodeGen;

/// <summary>Emits the generated half of the REST client.</summary>
internal sealed class Emitter(Spec spec, Map map)
{
    private const string Header = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     Generated by tools/MassiveDotNet.CodeGen from specs/openapi.json and
        //     specs/endpoints.map.json. Manual edits are overwritten on the next run.
        //     Hand-written members belong in the matching partial type instead.
        // </auto-generated>
        //------------------------------------------------------------------------------

        // The .g.cs suffix marks these files auto-generated, which suppresses the project's
        // nullable context, so it is re-enabled explicitly here.
        #nullable enable
        """;

    private const int UriBufferLength = 256;

    public Dictionary<string, string> Emit()
    {
        Dictionary<string, string> files = new(StringComparer.Ordinal);

        foreach (MapModel model in map.Models)
        {
            files[Path.Combine("Models", $"{model.Name}.g.cs")] = EmitModel(model);
        }

        // A map of body payloads alone has no envelope, and a file holding only usings would
        // fail the build under IDE0005.
        if (EmitEnvelopes() is { } envelopes)
        {
            files["Envelopes.g.cs"] = envelopes;
        }

        foreach (MapGroup group in map.Groups)
        {
            files[$"{group.Name}Group.g.cs"] = EmitGroup(group);
        }

        files["MassiveRestJsonContext.g.cs"] = EmitJsonContext();

        return files;
    }

    private string EmitModel(MapModel model)
    {
        SpecOperation operation = spec.Operation(model.SchemaOperationId);
        JsonElement schema = Spec.Navigate(Spec.SuccessSchema(operation), model.SchemaPointer);

        // Order by the map's declaration so related fields stay together (OHLCV rather than
        // the alphabetical order the OpenAPI document happens to store them in).
        List<string> declared = [.. model.Properties.Keys];
        List<SpecProperty> properties = [.. Spec.Properties(schema)
            .OrderBy(p => declared.IndexOf(p.Name) is var i and >= 0 ? i : int.MaxValue)];

        List<(SpecProperty Property, string Name, string Type, string? Summary)> members = [.. properties.Select(property =>
        {
            model.Properties.TryGetValue(property.Name, out MapProperty? mapped);

            return (
                property,
                mapped?.Name ?? Naming.Pascal(property.Name),
                PropertyType(model, property, mapped),
                mapped?.Summary ?? Prose.Clean(property.Description));
        })];

        CodeWriter writer = new();
        writer.Line(Header);
        writer.Line();
        writer.Line("using System.Text.Json.Serialization;");

        // Emitted conditionally: an unused using fails the build under EnforceCodeStyleInBuild.
        if (members.Exists(m => NamesNodaTime(m.Type)))
        {
            writer.Line("using NodaTime;");
        }

        writer.Line();
        writer.Line("namespace MassiveDotNet.Rest.Models;");
        writer.Line();

        writer.Doc("summary", model.Summary, preserveMarkup: true);
        writer.Doc("remarks", model.Remarks, preserveMarkup: true);

        string declaration = model.Kind == "struct"
            ? $"public readonly partial record struct {model.Name}"
            : $"public sealed partial record {model.Name}";

        using (writer.Block(declaration))
        {
            bool first = true;

            foreach ((SpecProperty property, string name, string type, string? summary) in members)
            {
                if (!first)
                {
                    writer.Line();
                }

                first = false;

                writer.Doc("summary", summary);
                writer.Line($"[JsonPropertyName(\"{property.Name}\")]");

                string modifier = NeedsRequiredModifier(property.Required, type) ? "required " : "";
                writer.Line($"public {modifier}{type} {name} {{ get; init; }}");
            }
        }

        return writer.ToString();
    }

    private string? EmitEnvelopes()
    {
        // Hoisted for the reason EmitModel hoists its members: the file's usings depend on the
        // types it emits, so those have to be resolved before the first line is written.
        List<(MapEndpoint Endpoint, SpecOperation Operation, ResultShape Shape, string ResultsProperty, List<(SpecProperty Property, string Type)> Members)> envelopes = [];

        foreach (MapEndpoint endpoint in map.Endpoints)
        {
            SpecOperation operation = spec.Operation(endpoint.OperationId);

            ValidateResultReuse(endpoint, operation);
            ResultShape shape = Shape(endpoint, operation);

            // A body payload deserializes as the model itself, so there is no envelope (D-S5).
            if (shape.Property is not { } property)
            {
                continue;
            }

            List<(SpecProperty Property, string Type)> members = [.. Spec.Properties(Spec.SuccessSchema(operation))
                .Select(p => (p, p.Name == property ? $"{shape.PayloadType}?" : EnvelopeType(endpoint, p)))];

            envelopes.Add((endpoint, operation, shape, Naming.Pascal(property), members));
        }

        if (envelopes.Count == 0)
        {
            return null;
        }

        CodeWriter writer = new();
        writer.Line(Header);
        writer.Line();
        writer.Line("using System.Text.Json.Serialization;");

        // Emitted conditionally: an unused using fails the build under EnforceCodeStyleInBuild.
        // Exists is order-independent, so rule 6 holds.
        if (envelopes.Exists(e => e.Shape.Enumerates))
        {
            writer.Line("using MassiveDotNet.Http;");
        }

        writer.Line("using MassiveDotNet.Rest.Models;");

        // An envelope can name a NodaTime type in its own right, when the description declares a
        // format: date or date-time property beside the payload.
        if (envelopes.Exists(e => e.Members.Exists(m => NamesNodaTime(m.Type))))
        {
            writer.Line("using NodaTime;");
        }

        writer.Line();
        writer.Line("namespace MassiveDotNet.Rest.Serialization;");

        foreach ((MapEndpoint endpoint, SpecOperation operation, ResultShape shape, string resultsProperty, List<(SpecProperty Property, string Type)> members) in envelopes)
        {
            writer.Line();
            writer.Doc("summary", $"The response envelope returned by {operation.Path}.");

            string declaration = shape.Enumerates
                ? $"internal sealed class {EnvelopeName(endpoint)} : IPagedEnvelope<{shape.ItemType}>"
                : $"internal sealed class {EnvelopeName(endpoint)}";

            using (writer.Block(declaration))
            {
                bool first = true;

                foreach ((SpecProperty property, string type) in members)
                {
                    if (!first)
                    {
                        writer.Line();
                    }

                    first = false;

                    writer.Doc("summary", Prose.Clean(property.Description));
                    writer.Line($"[JsonPropertyName(\"{property.Name}\")]");
                    writer.Line($"public {type} {Naming.Pascal(property.Name)} {{ get; init; }}");
                }

                if (shape.Items is { } items)
                {
                    // The page's items sit one level down, inside the result object, so the
                    // interface is satisfied explicitly through it (D-S2).
                    writer.Line();
                    writer.Line($"{items.Model}[]? IPagedEnvelope<{items.Model}>.Results => {resultsProperty}?.{items.Property};");
                }
                else if (shape.Enumerates && resultsProperty != "Results")
                {
                    // The interface names the results property `Results`. When the endpoint's result
                    // property maps to some other name, satisfy it explicitly rather than renaming
                    // the public property away from the wire shape.
                    writer.Line();
                    writer.Line($"{shape.ItemType}[]? IPagedEnvelope<{shape.ItemType}>.Results => {resultsProperty};");
                }
            }
        }

        return writer.ToString();
    }

    private string EmitGroup(MapGroup group)
    {
        List<MapEndpoint> endpoints = [.. map.Endpoints.Where(e => e.Group == group.Name)];

        CodeWriter writer = new();
        writer.Line(Header);
        writer.Line();
        // Emitted conditionally: an unused using fails the build under EnforceCodeStyleInBuild.
        // Any is order-independent, so rule 6 holds.
        bool needsNodaTime = endpoints.Any(e =>
            Arguments(e, spec.Operation(e.OperationId)).Exists(a => NamesNodaTime(a.CSharpType)));

        // HttpStatusCode is named only by the throw a singular Send method emits (D-S4). Exists is
        // order-independent, so rule 6 holds.
        bool needsSystemNet = endpoints.Exists(e => Shape(e, spec.Operation(e.OperationId)).ThrowsOnMissingPayload);

        if (needsSystemNet)
        {
            writer.Line("using System.Net;");
        }

        writer.Line("using MassiveDotNet.Http;");
        writer.Line("using MassiveDotNet.Rest.Models;");
        writer.Line("using MassiveDotNet.Rest.Serialization;");

        if (needsNodaTime)
        {
            writer.Line("using NodaTime;");
        }

        writer.Line();
        writer.Line("namespace MassiveDotNet.Rest;");
        writer.Line();

        using (writer.Block($"public readonly partial struct {group.Name}Group"))
        {
            bool first = true;

            foreach (MapEndpoint endpoint in endpoints)
            {
                if (!first)
                {
                    writer.Line();
                }

                first = false;
                EmitEndpoint(writer, endpoint);
            }
        }

        return writer.ToString();
    }

    private void EmitEndpoint(CodeWriter writer, MapEndpoint endpoint)
    {
        SpecOperation operation = spec.Operation(endpoint.OperationId);
        List<Argument> arguments = Arguments(endpoint, operation);
        ResultShape shape = Shape(endpoint, operation);

        // A request identifier is not universal: the futures AggregatesV1 envelope declares only
        // next_url, results, and status, so emitting response?.RequestId unconditionally would not
        // compile for it. The question asked is exactly the one that matters -- will the emitted
        // envelope have a RequestId property -- and Exists is order-independent, so rule 6 holds.
        bool hasRequestId = shape.HasEnvelope
            && Spec.Properties(Spec.SuccessSchema(operation))
                .Exists(p => Naming.Pascal(p.Name) == "RequestId");

        // Derived once: it is what both generated methods cross-reference, and deriving it is
        // what rejects a paginated endpoint whose mapped method is not List-prefixed.
        string enumerate = shape.Enumerates ? Naming.Enumerate(endpoint.Method, endpoint.OperationId) : string.Empty;
        string callArguments = string.Join(", ", arguments.Select(a => a.Identifier));
        // Nullable because Prose.Clean returns null for blank prose; Doc skips blank content.
        string? summary = endpoint.Summary ?? Prose.Clean(Summary(operation));
        bool preserve = endpoint.Summary is not null;

        if (shape.Enumerates)
        {
            // The two entry points share an endpoint but not a shape, so the enumerating one names
            // its own nature rather than repeating the summary verbatim: identical summaries are
            // indistinguishable in IntelliSense, where remarks are not shown.
            writer.Doc(
                "summary",
                AppendClause(summary, "enumerating every page as a single lazy sequence."),
                preserveMarkup: preserve);

            // A paginated object's other members belong to each page, and a flat sequence has
            // nowhere to attach them; the remark says so and points at List (D-S2).
            string remarks = shape.Items is { } items
                ? "Walks every page, requesting the next only once the previous one has been consumed, and "
                    + $"yields each page's <c>{items.WireName}</c> in turn; the other members of each page's "
                    + $"<c>{shape.Property}</c> are not observable through this sequence. "
                : "Walks every page, requesting the next only once the previous one has been consumed. ";

            remarks += $"Use <see cref=\"{endpoint.Method}Async\"/> to retrieve a single page instead.";

            // Emitted only where the endpoint declares the parameter, since not every paginated
            // operation has one. Exists is order-independent, so rule 6 holds.
            if (arguments.Exists(a => a.Identifier == "limit"))
            {
                remarks += " <paramref name=\"limit\"/> sizes each page rather than the traversal, so "
                    + "lowering it issues more requests rather than returning fewer items; bound the "
                    + "sequence with <c>Take</c> instead.";
            }

            // Added to, never replaced: the map carries what the spec cannot, so dropping its
            // remarks here would lose prose that no regeneration could recover.
            if (endpoint.Remarks is { } authored)
            {
                remarks = $"{remarks} {authored}";
            }

            writer.Doc("remarks", remarks, preserveMarkup: true);

            EmitParameterDocs(writer, arguments, "A token to cancel the traversal.");
            writer.Doc(
                "returns",
                shape.Items is { } enumerated
                    ? $"Every <c>{enumerated.WireName}</c> entry across every page."
                    : $"Every <c>{shape.Property}</c> item across every page.",
                preserveMarkup: true);
            writer.Doc("exception", "The server responded with an error status.", "cref=\"MassiveApiException\"");

            List<string> enumerateSignature = Signature(
                $"public IAsyncEnumerable<{shape.ItemType}> {enumerate}Async",
                [.. arguments.Select(a => a.Declaration), "CancellationToken cancellationToken = default"]);

            using (writer.Block(enumerateSignature))
            {
                EmitGuards(writer, arguments);
                writer.Line($"string requestUri = Build{endpoint.Method}Uri({callArguments});");
                writer.Line($"return _transport.EnumerateAsync<{EnvelopeName(endpoint)}, {shape.ItemType}>(");
                writer.Line($"    requestUri, MassiveRestJsonContext.Default.{EnvelopeName(endpoint)}, cancellationToken);");
            }

            writer.Line();
        }

        writer.Doc("summary", summary, preserveMarkup: preserve);

        // List is the more discoverable of the two names, so it is the one whose reader is most
        // likely not to know the other exists. The cross-reference points both ways.
        string? listRemarks = endpoint.Remarks;

        if (shape.Enumerates)
        {
            string pointer =
                $"Returns the first page only. Use <see cref=\"{enumerate}Async\"/> "
                + "to walk every page without handling cursors yourself.";

            listRemarks = listRemarks is null ? pointer : $"{pointer} {listRemarks}";
        }

        writer.Doc("remarks", listRemarks, preserveMarkup: true);

        EmitParameterDocs(writer, arguments, "A token to cancel the request.");
        writer.Doc("returns", Returns(shape), preserveMarkup: true);
        writer.Doc(
            "exception",
            shape.ThrowsOnMissingPayload
                ? "The server responded with an error status, or with a success that carried no payload."
                : "The server responded with an error status.",
            "cref=\"MassiveApiException\"");

        List<string> signature = Signature(
            $"public Task<{shape.ReturnType}> {endpoint.Method}Async",
            [.. arguments.Select(a => a.Declaration), "CancellationToken cancellationToken = default"]);

        using (writer.Block(signature))
        {
            EmitGuards(writer, arguments);
            writer.Line($"string requestUri = Build{endpoint.Method}Uri({callArguments});");
            writer.Line($"return Send{endpoint.Method}Async(requestUri, cancellationToken);");
        }

        writer.Line();

        // The URI builder is a ref struct, so it cannot live inside an async method.
        // Composition therefore happens in a separate synchronous method.
        List<string> builderSignature = Signature(
            $"private static string Build{endpoint.Method}Uri",
            [.. arguments.Select(a => a.RequiredDeclaration)]);

        using (writer.Block(builderSignature))
        {
            writer.Line($"RequestUriBuilder builder = new(stackalloc char[{UriBufferLength}]);");
            writer.Line();

            EmitPath(writer, operation.Path, arguments);

            foreach (Argument argument in arguments.Where(a => a.In == "query"))
            {
                writer.Line($"builder.AppendQuery(\"{argument.WireName}\", {argument.QueryExpression});");
            }

            writer.Line();
            writer.Line("return builder.ToUriString();");
        }

        writer.Line();

        EmitSend(writer, endpoint, shape, hasRequestId);
    }

    /// <summary>The <c>returns</c> sentence of the <c>List</c> or <c>Get</c> method, one per row of the D-S1 table.</summary>
    private static string Returns(ResultShape shape)
    {
        if (shape.Property is not { } property)
        {
            return shape.IsArray
                ? "The response body, an array that is empty when the server returned none."
                : "The response body, deserialized as one object.";
        }

        return (shape.IsArray, shape.Paginated, shape.Items) switch
        {
            (true, true, _) => $"A single page of <c>{property}</c>, reporting whether more exist.",
            (true, false, _) => $"The <c>{property}</c> array from the response, empty when the server returned none.",
            (false, true, not null) => $"A single page: the <c>{property}</c> object, reporting whether more exist.",
            _ => $"The <c>{property}</c> object from the response.",
        };
    }

    /// <summary>Emits the <c>Send</c> method: the one place a response is turned into the return type.</summary>
    private static void EmitSend(CodeWriter writer, MapEndpoint endpoint, ResultShape shape, bool hasRequestId)
    {
        using (writer.Block($"private async Task<{shape.ReturnType}> Send{endpoint.Method}Async(string requestUri, CancellationToken cancellationToken)"))
        {
            if (shape.Property is not { } property)
            {
                EmitBodySend(writer, shape);
                return;
            }

            string envelope = EnvelopeName(endpoint);
            string results = Naming.Pascal(property);
            string requestId = hasRequestId ? "response?.RequestId" : "requestId: null";

            writer.Line($"{envelope}? response = await _transport");
            writer.Line($"    .GetAsync(requestUri, MassiveRestJsonContext.Default.{envelope}, cancellationToken)");
            writer.Line("    .ConfigureAwait(false);");
            writer.Line();

            if (shape.IsArray && shape.Paginated)
            {
                // Emitted, not just reasoned about here: a reader of the generated file meets
                // a whitespace test on a URL and deserves to know it is load-bearing.
                writer.Line("// A blank next_url is not a cursor. EnumerateAsync stops on one, so this");
                writer.Line("// reports the same thing rather than promising a page that is never fetched.");

                if (!hasRequestId)
                {
                    writer.Line("// This operation's envelope declares no request_id, so there is none to report.");
                }

                writer.Line($"return new MassivePage<{shape.Model.Name}>(");
                writer.Line($"    response?.{results},");
                writer.Line("    !string.IsNullOrWhiteSpace(response?.NextUrl),");
                writer.Line($"    {requestId});");
                return;
            }

            if (shape.IsArray)
            {
                writer.Line($"return response?.{results} ?? [];");
                return;
            }

            if (shape.Paginated && shape.Items is null)
            {
                writer.Line("// The schema declares next_url, but one object cannot be paged, so a cursor here is a");
                writer.Line("// page the caller would never receive. A blank one passes; a real one throws (D17).");
                writer.Line($"MassiveHttpTransport.ThrowIfUnfollowableCursor(response?.NextUrl, requestUri, {requestId});");
                writer.Line();
            }

            // The throw for a missing payload, shared by the paged and plain singular shapes. Its
            // request id line is emitted only where the envelope has one to report.
            string[] missingPayload = hasRequestId
                ? [
                    "    ?? throw new MassiveApiException(",
                    "        HttpStatusCode.OK,",
                    $"        $\"The response from '{{requestUri}}' carried no '{property}' payload.\",",
                    "        response?.RequestId);",
                ]
                : [
                    "    ?? throw new MassiveApiException(",
                    "        HttpStatusCode.OK,",
                    $"        $\"The response from '{{requestUri}}' carried no '{property}' payload.\");",
                ];

            writer.Line("// A 200 without its payload is a success the caller cannot use, so it is reported the");
            writer.Line("// same way as a body that fails to deserialize rather than as null on every call (D17).");

            if (shape.Items is null)
            {
                writer.Line($"return response?.{results}");

                foreach (string line in missingPayload)
                {
                    writer.Line(line);
                }

                return;
            }

            // The local is what lets the page below read `response` without a null-conditional:
            // a non-null `response?.Results` proves `response` non-null to the compiler.
            writer.Line($"{shape.Model.Name} result = response?.{results}");

            foreach (string line in missingPayload)
            {
                writer.Line(line);
            }

            writer.Line();
            writer.Line("// A blank next_url is not a cursor. EnumerateAsync stops on one, so this");
            writer.Line("// reports the same thing rather than promising a page that is never fetched.");
            writer.Line($"return new MassivePagedResult<{shape.Model.Name}>(");
            writer.Line("    result,");
            writer.Line("    !string.IsNullOrWhiteSpace(response.NextUrl),");
            writer.Line(hasRequestId ? "    response.RequestId);" : "    requestId: null);");
        }
    }

    /// <summary>Emits the body of a <c>Send</c> method whose payload is the response body itself (D-S5).</summary>
    private static void EmitBodySend(CodeWriter writer, ResultShape shape)
    {
        // The context names an array's metadata property by its element type plus Array.
        string typeInfo = shape.IsArray ? $"{shape.Model.Name}Array" : shape.Model.Name;

        writer.Line($"{shape.PayloadType}? response = await _transport");
        writer.Line($"    .GetAsync(requestUri, MassiveRestJsonContext.Default.{typeInfo}, cancellationToken)");
        writer.Line("    .ConfigureAwait(false);");
        writer.Line();

        if (shape.IsArray)
        {
            writer.Line("return response ?? [];");
            return;
        }

        writer.Line("// An empty body is a success the caller cannot use, reported the same way as a body that");
        writer.Line("// fails to deserialize (D17). There is no envelope here, so no request id can be reported.");
        writer.Line("return response");
        writer.Line("    ?? throw new MassiveApiException(");
        writer.Line("        HttpStatusCode.OK,");
        writer.Line("        $\"The response from '{requestUri}' carried no payload.\");");
    }

    /// <summary>
    /// Every parameter the endpoint's methods take, required first, otherwise in the
    /// description's declaration order with each comparator group standing where its base
    /// field was declared.
    /// </summary>
    private List<Argument> Arguments(MapEndpoint endpoint, SpecOperation operation)
    {
        List<ParameterSlot> slots = Spec.Slots(spec.Parameters(operation));
        ValidateMapKeys(endpoint, slots);

        return [.. slots
            .Select(s => Argument.Create(s, endpoint.Parameters.GetValueOrDefault(s.WireName), endpoint.OperationId))
            .OrderByDescending(a => a.Required)];
    }

    /// <summary>
    /// A map row that names nothing the operation declares is a typo that would otherwise be
    /// ignored without a word. Grouping adds a second way to be wrong that looks right: a row
    /// keyed by a variant such as <c>ticker.gte</c> does nothing, because the group is keyed by
    /// its base name.
    /// </summary>
    private static void ValidateMapKeys(MapEndpoint endpoint, List<ParameterSlot> slots)
    {
        foreach (string key in endpoint.Parameters.Keys.Order(StringComparer.Ordinal))
        {
            if (!slots.Exists(s => s.WireName == key))
            {
                throw new InvalidOperationException(
                    $"Operation '{endpoint.OperationId}' maps parameter '{key}', which it does not declare. "
                    + "Rows are keyed by the field's base name: comparator variants such as 'ticker.gte' "
                    + "are grouped under 'ticker'.");
            }
        }
    }

    /// <summary>The NodaTime types the generator can emit, per the vocabulary table in CLAUDE.md.</summary>
    private static readonly HashSet<string> NodaTimeTypes = new(StringComparer.Ordinal)
    {
        "Instant",
        "LocalDate",
        "LocalDateTime",
        "ZonedDateTime",
        "Duration",
    };

    /// <summary>Separators that split an emitted type name into the identifiers it names.</summary>
    private static readonly char[] TypeNameSeparators = ['<', '>', ',', ' ', '?', '[', ']'];

    /// <summary>Whether a C# type name needs <c>using NodaTime;</c> in the file that declares it.</summary>
    /// <remarks>
    /// Matches whole identifiers rather than substrings, in both directions. A generic argument
    /// counts, so <c>RangeFilter&lt;LocalDate&gt;?</c> is caught; a type merely containing one of
    /// these names as a substring does not, since an unused using is itself a build failure
    /// under IDE0005.
    /// </remarks>
    /// <param name="type">An emitted type name, nullable annotation and generic arguments included.</param>
    /// <returns><see langword="true"/> when the type names a NodaTime type.</returns>
    private static bool NamesNodaTime(string type) =>
        Array.Exists(type.Split(TypeNameSeparators, StringSplitOptions.RemoveEmptyEntries), NodaTimeTypes.Contains);

    /// <summary>
    /// Whether a schema-required property needs the C# <c>required</c> modifier to satisfy
    /// nullable reference analysis.
    /// </summary>
    /// <remarks>
    /// A required value type already has a non-null default and needs nothing; a required
    /// reference type does not: the compiler-synthesized constructor exits without assigning it,
    /// which is CS8618 under this repository's warnings-as-errors build. The schema calling the
    /// field required is the fact being encoded -- <c>required</c> states it honestly, rather than
    /// an initializer such as <c>= null!</c> that pretends a value exists before one is read, or a
    /// nullable annotation that pretends the field might be absent when the schema says it never
    /// is. Value types are a closed set (D-N6): the scalars the generator emits, the NodaTime
    /// types, and any <c>struct</c> model. Everything else -- <c>string</c>, arrays, class models,
    /// a map-supplied <c>Dictionary&lt;string, T&gt;</c> -- is a reference type and gets the
    /// modifier, which is the safe direction: a missing modifier is CS8618 in this build, so it
    /// cannot ship. A spurious modifier on a value type is not a compile error -- C# allows
    /// <c>required</c> on a member of any type -- but System.Text.Json then demands the key at
    /// deserialization time, which is wrong for a field the schema does not require. Read from the
    /// resolved type string alone, so the check is order-independent and rule 6 holds.
    /// </remarks>
    /// <param name="required">Whether the schema declares the property required.</param>
    /// <param name="type">The property's resolved C# type, nullable annotation included.</param>
    /// <returns><see langword="true"/> when the property needs the <c>required</c> modifier.</returns>
    private bool NeedsRequiredModifier(bool required, string type) =>
        required
        && !type.EndsWith('?')
        && !ValueTypes.Contains(type)
        && !map.Models.Exists(m => m.Name == type && m.Kind == "struct");

    /// <summary>The value types the generator emits on models (D-N6). Extend with the vocabulary, never ad hoc.</summary>
    private static readonly HashSet<string> ValueTypes = new(StringComparer.Ordinal)
    {
        "int",
        "long",
        "double",
        "bool",
        "LocalDate",
        "Instant",
    };

    /// <summary>The array inside a paginated object that carries the page's items (D-S2).</summary>
    /// <param name="WireName">The property's wire name, as the model row's <c>items</c> declares it.</param>
    /// <param name="Property">The property's C# name on the model.</param>
    /// <param name="Model">The item model, which <c>Enumerate</c> yields.</param>
    private sealed record ItemBinding(string WireName, string Property, string Model);

    /// <summary>How an endpoint delivers its payload, and therefore what its methods return (D-S1).</summary>
    /// <param name="Model">The row of the model the payload is made of.</param>
    /// <param name="IsArray">Whether the payload is an array of the model rather than one of it.</param>
    /// <param name="Property">The envelope property holding the payload, or <see langword="null"/> when the body is the payload (D-S5).</param>
    /// <param name="Paginated">Whether the success schema declares <c>next_url</c> (D-P6).</param>
    /// <param name="Items">For a paginated object whose model row names <c>items</c>: the array <c>Enumerate</c> walks. Otherwise <see langword="null"/>.</param>
    private sealed record ResultShape(MapModel Model, bool IsArray, string? Property, bool Paginated, ItemBinding? Items)
    {
        /// <summary>Whether the payload sits on an envelope. Body payloads have none.</summary>
        public bool HasEnvelope => Property is not null;

        /// <summary>Whether an <c>Enumerate</c> counterpart is emitted: a paginated array, or a paginated object with <c>items</c>.</summary>
        public bool Enumerates => Paginated && (IsArray || Items is not null);

        /// <summary>The type <c>Enumerate</c> yields, and the envelope's <c>IPagedEnvelope</c> argument.</summary>
        public string ItemType => Items?.Model ?? Model.Name;

        /// <summary>The C# type of the payload itself: the model, or an array of it.</summary>
        public string PayloadType => IsArray ? $"{Model.Name}[]" : Model.Name;

        /// <summary>What the <c>List</c> or <c>Get</c> method returns: the D-S1 table, one arm per row.</summary>
        public string ReturnType => (IsArray, Paginated, Items) switch
        {
            (true, true, _) => $"MassivePage<{Model.Name}>",
            (true, false, _) => $"{Model.Name}[]",
            (false, true, not null) => $"MassivePagedResult<{Model.Name}>",
            _ => Model.Name,
        };

        /// <summary>Whether the <c>Send</c> method throws for an absent payload: every singular shape does (D-S4); arrays coalesce to empty.</summary>
        public bool ThrowsOnMissingPayload => !IsArray;
    }

    /// <summary>
    /// Resolves an endpoint's result row into the shape its methods take (D-S1). Every emitter that
    /// touches an endpoint reads this rather than the row, so the table lives in one place.
    /// </summary>
    private ResultShape Shape(MapEndpoint endpoint, SpecOperation operation)
    {
        MapModel model = ResultModel(endpoint);
        bool isArray = IsArrayKind(endpoint);
        bool paginated = Spec.IsPaginated(operation);

        // A body payload has no envelope to carry a cursor, so a root-level next_url is a shape the
        // D-S1 table has no row for. Refusing is what keeps that cursor from being dropped silently.
        if (paginated && endpoint.Result.Property is null)
        {
            throw new InvalidOperationException(
                $"Endpoint '{endpoint.Method}' (operation '{endpoint.OperationId}'): result declares no \"property\", so the "
                + "body is the payload, but the success schema declares next_url at its root. A body payload cannot "
                + "carry a cursor; name the payload property in \"result\" instead.");
        }

        // items matters only where the spec says there is a cursor and the payload is one object;
        // on any other model the key is harmless and ignored (D-S2).
        ItemBinding? items = !isArray && paginated ? ItemsOf(model) : null;

        return new ResultShape(model, isArray, endpoint.Result.Property, paginated, items);
    }

    /// <summary>The model an endpoint's result row names, which must be declared.</summary>
    private MapModel ResultModel(MapEndpoint endpoint) =>
        map.Models.Find(m => m.Name == endpoint.Result.Model)
            ?? throw new InvalidOperationException(
                $"Endpoint '{endpoint.Method}' (operation '{endpoint.OperationId}'): result names model "
                + $"'{endpoint.Result.Model}', which is not declared in \"models\" in specs/endpoints.map.json.");

    /// <summary>Whether the result row's kind is <c>array</c>; <c>object</c> is the only other kind, and anything else is refused (D-S1).</summary>
    private static bool IsArrayKind(MapEndpoint endpoint) => endpoint.Result.Kind switch
    {
        "array" => true,
        "object" => false,
        _ => throw new InvalidOperationException(
            $"Endpoint '{endpoint.Method}' (operation '{endpoint.OperationId}'): result kind '{endpoint.Result.Kind}' is not "
            + "recognised. Use \"array\" for an array of the model or \"object\" for a single one (D-S1)."),
    };

    /// <summary>
    /// The array a paginated object enumerates, read from the model row's <c>items</c> (D-S2) and
    /// verified against the schema (D-S6): the property exists, is an array of objects, and its
    /// row names a model. <see langword="null"/> when the row declares no <c>items</c>.
    /// </summary>
    private ItemBinding? ItemsOf(MapModel model)
    {
        if (model.Items is not { } items)
        {
            return null;
        }

        JsonElement schema = Spec.Navigate(Spec.SuccessSchema(spec.Operation(model.SchemaOperationId)), model.SchemaPointer);
        SpecProperty? property = Spec.Properties(schema).Find(p => p.Name == items);

        if (property is null)
        {
            throw new InvalidOperationException(
                $"Model '{model.Name}' (operation '{model.SchemaOperationId}'): \"items\" names '{items}', which the schema at "
                + $"{Located(model.SchemaPointer)} does not declare. Name the array property that carries the page's items.");
        }

        if (Spec.Shape(property.Schema) != SchemaShape.ArrayOfObjects)
        {
            throw new InvalidOperationException(
                $"Model '{model.Name}' (operation '{model.SchemaOperationId}'): \"items\" names '{items}', which is "
                + $"{Spec.Describe(Spec.Shape(property.Schema))}, not an array of objects. The items of a paginated object "
                + "are objects with a model of their own.");
        }

        if (!model.Properties.TryGetValue(items, out MapProperty? row) || row.Model is not { } itemModel)
        {
            throw new InvalidOperationException(
                $"Model '{model.Name}' (operation '{model.SchemaOperationId}'): \"items\" names '{items}', whose row does not "
                + $"name a \"model\". Add \"model\" to the '{items}' row; that model is what Enumerate yields.");
        }

        return new ItemBinding(items, row.Name ?? Naming.Pascal(items), itemModel);
    }

    /// <summary>A model's origin as it reads in a diagnostic: its pointer, or the response body for the root.</summary>
    private static string Located(string pointer) =>
        pointer.Length == 0 ? "the response body" : $"'{pointer}'";

    /// <summary>The pointer to a property of the schema at <paramref name="parent"/>, which may be the root.</summary>
    private static string ChildPointer(string parent, string segment) =>
        parent.Length == 0 ? segment : $"{parent}/{segment}";

    private static void EmitGuards(CodeWriter writer, List<Argument> arguments)
    {
        foreach (Argument argument in arguments.Where(a => a is { Required: true, CSharpType: "string" }))
        {
            writer.Line($"ArgumentException.ThrowIfNullOrWhiteSpace({argument.Identifier});");
        }
    }

    private static void EmitParameterDocs(CodeWriter writer, List<Argument> arguments, string cancellationDescription)
    {
        foreach (Argument argument in arguments)
        {
            writer.Doc("param", argument.Description, $"name=\"{argument.Identifier}\"");
        }

        writer.Doc("param", cancellationDescription, "name=\"cancellationToken\"");
    }

    private static void EmitPath(CodeWriter writer, string path, List<Argument> arguments)
    {
        StringBuilder literal = new();
        int index = 0;

        while (index < path.Length)
        {
            if (path[index] != '{')
            {
                literal.Append(path[index++]);
                continue;
            }

            int close = path.IndexOf('}', index);
            string name = path[(index + 1)..close];
            index = close + 1;

            if (literal.Length > 0)
            {
                writer.Line($"builder.AppendPathLiteral(\"{literal}\");");
                literal.Clear();
            }

            Argument argument = arguments.First(a => a.WireName == name);
            writer.Line($"builder.{argument.PathAppendMethod}({argument.PathExpression});");
        }

        if (literal.Length > 0)
        {
            writer.Line($"builder.AppendPathLiteral(\"{literal}\");");
        }

        writer.Line();
    }

    private string EmitJsonContext()
    {
        // An envelope carries its payload; a body payload has none, so the model itself, or an
        // array of it, is registered instead (D-S5). Kept in map order and deduplicated, since two
        // operations may share a body model, so rule 6 holds.
        List<string> registered = [];

        foreach (MapEndpoint endpoint in map.Endpoints)
        {
            ResultShape shape = Shape(endpoint, spec.Operation(endpoint.OperationId));
            string type = shape.HasEnvelope ? EnvelopeName(endpoint) : shape.PayloadType;

            if (!registered.Contains(type))
            {
                registered.Add(type);
            }
        }

        CodeWriter writer = new();
        writer.Line(Header);
        writer.Line();
        writer.Line("using System.Text.Json.Serialization;");

        // Emitted conditionally: an unused using fails the build under EnforceCodeStyleInBuild.
        if (map.Endpoints.Exists(e => e.Result.Property is null))
        {
            writer.Line("using MassiveDotNet.Rest.Models;");
        }

        writer.Line("using MassiveDotNet.Serialization;");
        writer.Line();
        writer.Line("namespace MassiveDotNet.Rest.Serialization;");
        writer.Line();
        writer.Doc("summary", "Source-generated serialization metadata for every REST response envelope. Using a context rather than reflection keeps the SDK Native AOT compatible.");
        writer.Doc("remarks", "Calendar dates are read by <see cref=\"LocalDateJsonConverter\"/> and RFC 3339 timestamps by <see cref=\"InstantJsonConverter\"/>, registered here once so no model property needs its own attribute.", preserveMarkup: true);
        writer.Line("[JsonSourceGenerationOptions(Converters = new[] { typeof(LocalDateJsonConverter), typeof(InstantJsonConverter) })]");

        foreach (string type in registered)
        {
            writer.Line($"[JsonSerializable(typeof({type}))]");
        }

        writer.Line("internal sealed partial class MassiveRestJsonContext : JsonSerializerContext;");

        return writer.ToString();
    }

    /// <summary>Wraps a parameter list one-per-line so long signatures stay readable.</summary>
    private static List<string> Signature(string prefix, IReadOnlyList<string> parameters)
    {
        // The closing paren rides on the last parameter below, so an empty list would never
        // produce one. Only the private Build...Uri of a parameterless operation reaches this:
        // every public entry point carries a cancellation token, which is why it went unnoticed
        // until the first such operation was mapped.
        if (parameters.Count == 0)
        {
            return [$"{prefix}()"];
        }

        List<string> lines = [$"{prefix}("];

        for (int i = 0; i < parameters.Count; i++)
        {
            string separator = i == parameters.Count - 1 ? ")" : ",";
            lines.Add($"    {parameters[i]}{separator}");
        }

        return lines;
    }

    private static string EnvelopeName(MapEndpoint endpoint) => $"{Naming.Pascal(endpoint.OperationId)}Response";

    private static string Summary(SpecOperation operation) =>
        operation.Operation.TryGetProperty("summary", out JsonElement summary)
            ? summary.GetString() ?? operation.OperationId
            : operation.OperationId;

    /// <summary>
    /// Appends a clause to a sentence so the result reads as one sentence, whether or not the
    /// source prose already ended in terminal punctuation.
    /// </summary>
    private static string? AppendClause(string? sentence, string clause) =>
        string.IsNullOrWhiteSpace(sentence)
            ? null
            : $"{sentence.TrimEnd().TrimEnd('.', '!', '?')}, {clause}";

    private static string DefaultPropertyType(SpecProperty property)
    {
        string type = TypeBinding.FromSchema(property.Schema);
        return property.Required || type == "string" ? Nullable(type, property.Required) : $"{type}?";
    }

    /// <summary>
    /// The C# type of a model property: the row's verbatim <c>type</c>, the model its row names
    /// (D-N2), or the schema's default. An object with neither is refused (D-N3).
    /// </summary>
    private string PropertyType(MapModel model, SpecProperty property, MapProperty? mapped)
    {
        if (mapped is { Model: not null, Type: not null })
        {
            throw new InvalidOperationException(
                $"Model '{model.Name}' (operation '{model.SchemaOperationId}'): property '{property.Name}' carries both "
                + "\"model\" and \"type\". A row names a model, whose nullability and array-ness the spec supplies, "
                + "or a verbatim type, never both.");
        }

        if (mapped?.Model is { } modelName)
        {
            return ModelReferenceType(model, property, modelName);
        }

        if (mapped?.Type is { } type)
        {
            return type;
        }

        if (TypeBinding.NeedsModel(property.Schema))
        {
            throw Unbound(model, property);
        }

        return DefaultPropertyType(property);
    }

    /// <summary>
    /// The diagnostic for an object with no binding: it names the row to add and the row to
    /// point at it, so the fix is a paste rather than a search (D-N3).
    /// </summary>
    private static InvalidOperationException Unbound(MapModel model, SpecProperty property)
    {
        SchemaShape shape = Spec.Shape(property.Schema);
        string described = Spec.Describe(shape);

        if (shape == SchemaShape.ArrayOfArrays)
        {
            return new InvalidOperationException(
                $"Operation '{model.SchemaOperationId}': property '{property.Name}' of model '{model.Name}' is {described}, "
                + "which has no binding. Set \"type\" on its row in specs/endpoints.map.json.");
        }

        string pointer = shape == SchemaShape.ArrayOfObjects
            ? $"{ChildPointer(model.SchemaPointer, property.Name)}/items"
            : ChildPointer(model.SchemaPointer, property.Name);

        return new InvalidOperationException(
            $"Operation '{model.SchemaOperationId}': property '{property.Name}' of model '{model.Name}' is {described} with no binding.\n"
            + "Add a row to \"models\" in specs/endpoints.map.json:\n"
            + $"  \"<Name>\": {{ \"schema\": {{ \"operationId\": \"{model.SchemaOperationId}\", \"pointer\": \"{pointer}\" }} }}\n"
            + $"and set \"model\": \"<Name>\" on the '{property.Name}' row of '{model.Name}'. "
            + "A free-form object with no declared properties takes \"type\" instead, such as \"Dictionary<string, double>\" (D-N6).");
    }

    /// <summary>
    /// Composes the type for a property whose row names a model: the model, or an array of it,
    /// nullable when the schema does not require the property (D-N2).
    /// </summary>
    private string ModelReferenceType(MapModel owner, SpecProperty property, string modelName)
    {
        MapModel target = map.Models.Find(m => m.Name == modelName)
            ?? throw new InvalidOperationException(
                $"Model '{owner.Name}' (operation '{owner.SchemaOperationId}'): property '{property.Name}' names model "
                + $"'{modelName}', which is not declared in \"models\" in specs/endpoints.map.json.");

        SchemaShape shape = Spec.Shape(property.Schema);

        if (shape is not (SchemaShape.Object or SchemaShape.ArrayOfObjects))
        {
            throw new InvalidOperationException(
                $"Model '{owner.Name}' (operation '{owner.SchemaOperationId}'): property '{property.Name}' names model "
                + $"'{modelName}', but its schema is {Spec.Describe(shape)}, not an object or an array of objects. "
                + "Use \"type\" for anything else.");
        }

        // A name may cover only one shape. The site is compared with the schema the model was
        // generated from, so a reused model is proven identical everywhere it appears (D-N4).
        // The comparison also runs where the site is the origin itself; a schema always matches
        // itself, so that costs nothing and needs no special case.
        JsonElement site = shape == SchemaShape.ArrayOfObjects ? property.Schema.GetProperty("items") : property.Schema;
        JsonElement origin = Spec.Navigate(Spec.SuccessSchema(spec.Operation(target.SchemaOperationId)), target.SchemaPointer);
        List<string> differences = Spec.StructuralDifferences(origin, site);

        if (differences.Count > 0)
        {
            throw new InvalidOperationException(
                $"Model '{owner.Name}' (operation '{owner.SchemaOperationId}'): property '{property.Name}' names model "
                + $"'{target.Name}', generated from operation '{target.SchemaOperationId}' at {Located(target.SchemaPointer)}, "
                + "but the schema at this site differs:\n  "
                + string.Join("\n  ", differences)
                + "\nA model name may cover only one shape. Declare a second model for this site, or fix the row.");
        }

        string type = shape == SchemaShape.ArrayOfObjects ? $"{target.Name}[]" : target.Name;

        return property.Required ? type : $"{type}?";
    }

    /// <summary>
    /// Verifies an endpoint's <c>result</c> row against the schema its named model was generated
    /// from, the same structural check <see cref="ModelReferenceType"/> runs where a model is
    /// named on a property (D-N4). The site is resolved by kind and location (D-S6): an object
    /// result is the named property or the body itself; an array result is that array's element.
    /// Runs once per endpoint, from <see cref="EmitEnvelopes"/>, so it is order-independent and
    /// rule 6 holds.
    /// </summary>
    private void ValidateResultReuse(MapEndpoint endpoint, SpecOperation operation)
    {
        MapModel target = ResultModel(endpoint);
        bool isArray = IsArrayKind(endpoint);
        JsonElement success = Spec.SuccessSchema(operation);
        JsonElement located = success;

        if (endpoint.Result.Property is { } property)
        {
            SpecProperty declared = Spec.Properties(success).Find(p => p.Name == property)
                ?? throw new InvalidOperationException(
                    $"Endpoint '{endpoint.Method}' (operation '{endpoint.OperationId}'): result names property '{property}', "
                    + "which the success schema does not declare. Name the property that carries the payload, or omit "
                    + "\"property\" when the body itself is the payload.");

            located = declared.Schema;
        }

        // A kind that disagrees with the schema is refused with the kind that would agree, so the
        // fix is a word rather than a search.
        SchemaShape expected = isArray ? SchemaShape.ArrayOfObjects : SchemaShape.Object;
        SchemaShape actual = Spec.Shape(located);

        if (actual != expected)
        {
            string where = endpoint.Result.Property is { } named ? $"'{named}'" : "the response body";
            string fix = actual switch
            {
                SchemaShape.Object => "Use kind \"object\" for a single model.",
                SchemaShape.ArrayOfObjects => "Use kind \"array\" for an array of the model.",
                _ => "Only an object or an array of objects can be a result.",
            };

            throw new InvalidOperationException(
                $"Endpoint '{endpoint.Method}' (operation '{endpoint.OperationId}'): result kind '{endpoint.Result.Kind}' "
                + $"expects {Spec.Describe(expected)} at {where}, but the schema there is {Spec.Describe(actual)}. {fix}");
        }

        JsonElement site = isArray ? located.GetProperty("items") : located;
        JsonElement origin = Spec.Navigate(Spec.SuccessSchema(spec.Operation(target.SchemaOperationId)), target.SchemaPointer);
        List<string> differences = Spec.StructuralDifferences(origin, site);

        if (differences.Count > 0)
        {
            throw new InvalidOperationException(
                $"Endpoint '{endpoint.Method}' (operation '{endpoint.OperationId}'): result names model "
                + $"'{target.Name}', generated from operation '{target.SchemaOperationId}' at {Located(target.SchemaPointer)}, "
                + "but the schema at this site differs:\n  "
                + string.Join("\n  ", differences)
                + "\nA model name may cover only one shape. Declare a second model for this site, or fix the row.");
        }
    }

    private static string NullableEnvelopeType(SpecProperty property)
    {
        string type = TypeBinding.FromSchema(property.Schema);
        return type == "string" ? "string?" : $"{type}?";
    }

    /// <summary>
    /// The type of an envelope property other than the payload. Envelopes have no map rows, so an
    /// object here is bound only by naming it as the result, or by making the body the result (D-S5).
    /// </summary>
    private static string EnvelopeType(MapEndpoint endpoint, SpecProperty property)
    {
        if (TypeBinding.NeedsModel(property.Schema))
        {
            throw new InvalidOperationException(
                $"Operation '{endpoint.OperationId}': envelope property '{property.Name}' is {Spec.Describe(Spec.Shape(property.Schema))}, "
                + "and only the payload named by the endpoint's \"result\" row is bound. If this property is the payload, "
                + $"set \"property\": \"{property.Name}\" on the result row; if the whole body is the payload, omit "
                + "\"property\" and declare the body as the result (D-S5).");
        }

        return NullableEnvelopeType(property);
    }

    private static string Nullable(string type, bool required) =>
        required ? type : $"{type}?";
}
