using System.Text;
using System.Text.Json;

namespace MassiveDotNet.CodeGen;

/// <summary>Emits the generated half of the REST client.</summary>
internal sealed class Emitter(Spec spec, Map map)
{
    private const string Header = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     Generated by tools/MassiveDotNet.CodeGen from specs/openapi.json and
        //     specs/endpoints.map.json. Manual edits are overwritten on the next run.
        //     Hand-written members belong in the matching partial type instead.
        // </auto-generated>
        //------------------------------------------------------------------------------

        // The .g.cs suffix marks these files auto-generated, which suppresses the project's
        // nullable context, so it is re-enabled explicitly here.
        #nullable enable
        """;

    private const int UriBufferLength = 256;

    public Dictionary<string, string> Emit()
    {
        Dictionary<string, string> files = new(StringComparer.Ordinal);

        foreach (MapModel model in map.Models)
        {
            files[Path.Combine("Models", $"{model.Name}.g.cs")] = EmitModel(model);
        }

        files["Envelopes.g.cs"] = EmitEnvelopes();

        foreach (MapGroup group in map.Groups)
        {
            files[$"{group.Name}Group.g.cs"] = EmitGroup(group);
        }

        files["MassiveRestJsonContext.g.cs"] = EmitJsonContext();

        return files;
    }

    private string EmitModel(MapModel model)
    {
        SpecOperation operation = spec.Operation(model.SchemaOperationId);
        JsonElement schema = Spec.Navigate(Spec.SuccessSchema(operation), model.SchemaPointer);

        // Order by the map's declaration so related fields stay together (OHLCV rather than
        // the alphabetical order the OpenAPI document happens to store them in).
        List<string> declared = [.. model.Properties.Keys];
        List<SpecProperty> properties = [.. Spec.Properties(schema)
            .OrderBy(p => declared.IndexOf(p.Name) is var i and >= 0 ? i : int.MaxValue)];

        List<(SpecProperty Property, string Name, string Type, string? Summary)> members = [.. properties.Select(property =>
        {
            model.Properties.TryGetValue(property.Name, out MapProperty? mapped);

            return (
                property,
                mapped?.Name ?? Naming.Pascal(property.Name),
                mapped?.Type ?? DefaultPropertyType(property),
                mapped?.Summary ?? Prose.Clean(property.Description));
        })];

        CodeWriter writer = new();
        writer.Line(Header);
        writer.Line();
        writer.Line("using System.Text.Json.Serialization;");

        // Emitted conditionally: an unused using fails the build under EnforceCodeStyleInBuild.
        if (members.Exists(m => NamesNodaTime(m.Type)))
        {
            writer.Line("using NodaTime;");
        }

        writer.Line();
        writer.Line("namespace MassiveDotNet.Rest.Models;");
        writer.Line();

        writer.Doc("summary", model.Summary, preserveMarkup: true);
        writer.Doc("remarks", model.Remarks, preserveMarkup: true);

        string declaration = model.Kind == "struct"
            ? $"public readonly partial record struct {model.Name}"
            : $"public sealed partial record {model.Name}";

        using (writer.Block(declaration))
        {
            bool first = true;

            foreach ((SpecProperty property, string name, string type, string? summary) in members)
            {
                if (!first)
                {
                    writer.Line();
                }

                first = false;

                writer.Doc("summary", summary);
                writer.Line($"[JsonPropertyName(\"{property.Name}\")]");

                string modifier = NeedsRequiredModifier(property.Required, type) ? "required " : "";
                writer.Line($"public {modifier}{type} {name} {{ get; init; }}");
            }
        }

        return writer.ToString();
    }

    private string EmitEnvelopes()
    {
        // Hoisted for the reason EmitModel hoists its members: the file's usings depend on the
        // types it emits, so those have to be resolved before the first line is written.
        List<(MapEndpoint Endpoint, SpecOperation Operation, bool Paginated, List<(SpecProperty Property, string Type)> Members)> envelopes =
            [.. map.Endpoints.Select(endpoint =>
            {
                SpecOperation operation = spec.Operation(endpoint.OperationId);

                List<(SpecProperty Property, string Type)> members = [.. Spec.Properties(Spec.SuccessSchema(operation))
                    .Select(property => (
                        property,
                        property.Name == endpoint.Result.Property
                            ? $"{endpoint.Result.Model}[]?"
                            : NullableEnvelopeType(property)))];

                return (endpoint, operation, Spec.IsPaginated(operation), members);
            })];

        CodeWriter writer = new();
        writer.Line(Header);
        writer.Line();
        writer.Line("using System.Text.Json.Serialization;");

        // Emitted conditionally: an unused using fails the build under EnforceCodeStyleInBuild.
        // Exists is order-independent, so rule 6 holds.
        if (envelopes.Exists(e => e.Paginated))
        {
            writer.Line("using MassiveDotNet.Http;");
        }

        writer.Line("using MassiveDotNet.Rest.Models;");

        // An envelope can name a NodaTime type in its own right: the open/close operations declare
        // a format: date property at the top level of their response, which binds to LocalDate.
        if (envelopes.Exists(e => e.Members.Exists(m => NamesNodaTime(m.Type))))
        {
            writer.Line("using NodaTime;");
        }

        writer.Line();
        writer.Line("namespace MassiveDotNet.Rest.Serialization;");

        foreach ((MapEndpoint endpoint, SpecOperation operation, bool paginated, List<(SpecProperty Property, string Type)> members) in envelopes)
        {
            writer.Line();
            writer.Doc("summary", $"The response envelope returned by {operation.Path}.");

            string declaration = paginated
                ? $"internal sealed class {EnvelopeName(endpoint)} : IPagedEnvelope<{endpoint.Result.Model}>"
                : $"internal sealed class {EnvelopeName(endpoint)}";

            using (writer.Block(declaration))
            {
                bool first = true;

                foreach ((SpecProperty property, string type) in members)
                {
                    if (!first)
                    {
                        writer.Line();
                    }

                    first = false;

                    writer.Doc("summary", Prose.Clean(property.Description));
                    writer.Line($"[JsonPropertyName(\"{property.Name}\")]");
                    writer.Line($"public {type} {Naming.Pascal(property.Name)} {{ get; init; }}");
                }

                // The interface names the results property `Results`. When the endpoint's result
                // property maps to some other name, satisfy it explicitly rather than renaming
                // the public property away from the wire shape.
                string resultsProperty = Naming.Pascal(endpoint.Result.Property);

                if (paginated && resultsProperty != "Results")
                {
                    writer.Line();
                    writer.Line(
                        $"{endpoint.Result.Model}[]? IPagedEnvelope<{endpoint.Result.Model}>.Results => {resultsProperty};");
                }
            }
        }

        return writer.ToString();
    }

    private string EmitGroup(MapGroup group)
    {
        List<MapEndpoint> endpoints = [.. map.Endpoints.Where(e => e.Group == group.Name)];

        CodeWriter writer = new();
        writer.Line(Header);
        writer.Line();
        // Emitted conditionally: an unused using fails the build under EnforceCodeStyleInBuild.
        // Any is order-independent, so rule 6 holds.
        bool needsNodaTime = endpoints.Any(e =>
            Arguments(e, spec.Operation(e.OperationId)).Exists(a => NamesNodaTime(a.CSharpType)));

        writer.Line("using MassiveDotNet.Http;");
        writer.Line("using MassiveDotNet.Rest.Models;");
        writer.Line("using MassiveDotNet.Rest.Serialization;");

        if (needsNodaTime)
        {
            writer.Line("using NodaTime;");
        }

        writer.Line();
        writer.Line("namespace MassiveDotNet.Rest;");
        writer.Line();

        using (writer.Block($"public readonly partial struct {group.Name}Group"))
        {
            bool first = true;

            foreach (MapEndpoint endpoint in endpoints)
            {
                if (!first)
                {
                    writer.Line();
                }

                first = false;
                EmitEndpoint(writer, endpoint);
            }
        }

        return writer.ToString();
    }

    private void EmitEndpoint(CodeWriter writer, MapEndpoint endpoint)
    {
        SpecOperation operation = spec.Operation(endpoint.OperationId);
        List<Argument> arguments = Arguments(endpoint, operation);
        bool paginated = Spec.IsPaginated(operation);

        // A request identifier is not universal: the futures AggregatesV1 envelope declares only
        // next_url, results, and status, so emitting response?.RequestId unconditionally would not
        // compile for it. The question asked is exactly the one that matters -- will the emitted
        // envelope have a RequestId property -- and Exists is order-independent, so rule 6 holds.
        bool hasRequestId = paginated
            && Spec.Properties(Spec.SuccessSchema(operation))
                .Exists(p => Naming.Pascal(p.Name) == "RequestId");

        string model = endpoint.Result.Model;
        string returnType = paginated ? $"MassivePage<{model}>" : $"{model}[]";
        // Derived once: it is what both generated methods cross-reference, and deriving it is
        // what rejects a paginated endpoint whose mapped method is not List-prefixed.
        string enumerate = paginated ? Naming.Enumerate(endpoint.Method, endpoint.OperationId) : string.Empty;
        string callArguments = string.Join(", ", arguments.Select(a => a.Identifier));
        // Nullable because Prose.Clean returns null for blank prose; Doc skips blank content.
        string? summary = endpoint.Summary ?? Prose.Clean(Summary(operation));
        bool preserve = endpoint.Summary is not null;

        if (paginated)
        {
            // The two entry points share an endpoint but not a shape, so the enumerating one names
            // its own nature rather than repeating the summary verbatim: identical summaries are
            // indistinguishable in IntelliSense, where remarks are not shown.
            writer.Doc(
                "summary",
                AppendClause(summary, "enumerating every page as a single lazy sequence."),
                preserveMarkup: preserve);

            string remarks =
                "Walks every page, requesting the next only once the previous one has been consumed. "
                + $"Use <see cref=\"{endpoint.Method}Async\"/> to retrieve a single page instead.";

            // Emitted only where the endpoint declares the parameter, since not every paginated
            // operation has one. Exists is order-independent, so rule 6 holds.
            if (arguments.Exists(a => a.Identifier == "limit"))
            {
                remarks += " <paramref name=\"limit\"/> sizes each page rather than the traversal, so "
                    + "lowering it issues more requests rather than returning fewer items; bound the "
                    + "sequence with <c>Take</c> instead.";
            }

            // Added to, never replaced: the map carries what the spec cannot, so dropping its
            // remarks here would lose prose that no regeneration could recover.
            if (endpoint.Remarks is { } authored)
            {
                remarks = $"{remarks} {authored}";
            }

            writer.Doc("remarks", remarks, preserveMarkup: true);

            EmitParameterDocs(writer, arguments, "A token to cancel the traversal.");
            writer.Doc(
                "returns",
                $"Every <c>{endpoint.Result.Property}</c> item across every page.",
                preserveMarkup: true);
            writer.Doc("exception", "The server responded with an error status.", "cref=\"MassiveApiException\"");

            List<string> enumerateSignature = Signature(
                $"public IAsyncEnumerable<{model}> {enumerate}Async",
                [.. arguments.Select(a => a.Declaration), "CancellationToken cancellationToken = default"]);

            using (writer.Block(enumerateSignature))
            {
                EmitGuards(writer, arguments);
                writer.Line($"string requestUri = Build{endpoint.Method}Uri({callArguments});");
                writer.Line($"return _transport.EnumerateAsync<{EnvelopeName(endpoint)}, {model}>(");
                writer.Line($"    requestUri, MassiveRestJsonContext.Default.{EnvelopeName(endpoint)}, cancellationToken);");
            }

            writer.Line();
        }

        writer.Doc("summary", summary, preserveMarkup: preserve);

        // List is the more discoverable of the two names, so it is the one whose reader is most
        // likely not to know the other exists. The cross-reference points both ways.
        string? listRemarks = endpoint.Remarks;

        if (paginated)
        {
            string pointer =
                $"Returns the first page only. Use <see cref=\"{enumerate}Async\"/> "
                + "to walk every page without handling cursors yourself.";

            listRemarks = listRemarks is null ? pointer : $"{pointer} {listRemarks}";
        }

        writer.Doc("remarks", listRemarks, preserveMarkup: true);

        EmitParameterDocs(writer, arguments, "A token to cancel the request.");

        writer.Doc(
            "returns",
            paginated
                ? $"A single page of <c>{endpoint.Result.Property}</c>, reporting whether more exist."
                : $"The <c>{endpoint.Result.Property}</c> array from the response, empty when the server returned none.",
            preserveMarkup: true);
        writer.Doc("exception", "The server responded with an error status.", "cref=\"MassiveApiException\"");

        List<string> signature = Signature(
            $"public Task<{returnType}> {endpoint.Method}Async",
            [.. arguments.Select(a => a.Declaration), "CancellationToken cancellationToken = default"]);

        using (writer.Block(signature))
        {
            EmitGuards(writer, arguments);
            writer.Line($"string requestUri = Build{endpoint.Method}Uri({callArguments});");
            writer.Line($"return Send{endpoint.Method}Async(requestUri, cancellationToken);");
        }

        writer.Line();

        // The URI builder is a ref struct, so it cannot live inside an async method.
        // Composition therefore happens in a separate synchronous method.
        List<string> builderSignature = Signature(
            $"private static string Build{endpoint.Method}Uri",
            [.. arguments.Select(a => a.RequiredDeclaration)]);

        using (writer.Block(builderSignature))
        {
            writer.Line($"RequestUriBuilder builder = new(stackalloc char[{UriBufferLength}]);");
            writer.Line();

            EmitPath(writer, operation.Path, arguments);

            foreach (Argument argument in arguments.Where(a => a.In == "query"))
            {
                writer.Line($"builder.AppendQuery(\"{argument.WireName}\", {argument.QueryExpression});");
            }

            writer.Line();
            writer.Line("return builder.ToUriString();");
        }

        writer.Line();

        using (writer.Block($"private async Task<{returnType}> Send{endpoint.Method}Async(string requestUri, CancellationToken cancellationToken)"))
        {
            writer.Line($"{EnvelopeName(endpoint)}? response = await _transport");
            writer.Line($"    .GetAsync(requestUri, MassiveRestJsonContext.Default.{EnvelopeName(endpoint)}, cancellationToken)");
            writer.Line("    .ConfigureAwait(false);");
            writer.Line();

            if (paginated)
            {
                // Emitted, not just reasoned about here: a reader of the generated file meets
                // a whitespace test on a URL and deserves to know it is load-bearing.
                writer.Line("// A blank next_url is not a cursor. EnumerateAsync stops on one, so this");
                writer.Line("// reports the same thing rather than promising a page that is never fetched.");

                if (!hasRequestId)
                {
                    writer.Line("// This operation's envelope declares no request_id, so there is none to report.");
                }

                writer.Line($"return new MassivePage<{model}>(");
                writer.Line($"    response?.{Naming.Pascal(endpoint.Result.Property)},");
                writer.Line("    !string.IsNullOrWhiteSpace(response?.NextUrl),");
                writer.Line(hasRequestId ? "    response?.RequestId);" : "    requestId: null);");
            }
            else
            {
                writer.Line($"return response?.{Naming.Pascal(endpoint.Result.Property)} ?? [];");
            }
        }
    }

    /// <summary>
    /// Every parameter the endpoint's methods take, required first, otherwise in the
    /// description's declaration order with each comparator group standing where its base
    /// field was declared.
    /// </summary>
    private List<Argument> Arguments(MapEndpoint endpoint, SpecOperation operation)
    {
        List<ParameterSlot> slots = Spec.Slots(spec.Parameters(operation));
        ValidateMapKeys(endpoint, slots);

        return [.. slots
            .Select(s => Argument.Create(s, endpoint.Parameters.GetValueOrDefault(s.WireName), endpoint.OperationId))
            .OrderByDescending(a => a.Required)];
    }

    /// <summary>
    /// A map row that names nothing the operation declares is a typo that would otherwise be
    /// ignored without a word. Grouping adds a second way to be wrong that looks right: a row
    /// keyed by a variant such as <c>ticker.gte</c> does nothing, because the group is keyed by
    /// its base name.
    /// </summary>
    private static void ValidateMapKeys(MapEndpoint endpoint, List<ParameterSlot> slots)
    {
        foreach (string key in endpoint.Parameters.Keys.Order(StringComparer.Ordinal))
        {
            if (!slots.Exists(s => s.WireName == key))
            {
                throw new InvalidOperationException(
                    $"Operation '{endpoint.OperationId}' maps parameter '{key}', which it does not declare. "
                    + "Rows are keyed by the field's base name: comparator variants such as 'ticker.gte' "
                    + "are grouped under 'ticker'.");
            }
        }
    }

    /// <summary>The NodaTime types the generator can emit, per the vocabulary table in CLAUDE.md.</summary>
    private static readonly HashSet<string> NodaTimeTypes = new(StringComparer.Ordinal)
    {
        "Instant",
        "LocalDate",
        "LocalDateTime",
        "ZonedDateTime",
        "Duration",
    };

    /// <summary>Separators that split an emitted type name into the identifiers it names.</summary>
    private static readonly char[] TypeNameSeparators = ['<', '>', ',', ' ', '?', '[', ']'];

    /// <summary>Whether a C# type name needs <c>using NodaTime;</c> in the file that declares it.</summary>
    /// <remarks>
    /// Matches whole identifiers rather than substrings, in both directions. A generic argument
    /// counts, so <c>RangeFilter&lt;LocalDate&gt;?</c> is caught; a type merely containing one of
    /// these names as a substring does not, since an unused using is itself a build failure
    /// under IDE0005.
    /// </remarks>
    /// <param name="type">An emitted type name, nullable annotation and generic arguments included.</param>
    /// <returns><see langword="true"/> when the type names a NodaTime type.</returns>
    private static bool NamesNodaTime(string type) =>
        Array.Exists(type.Split(TypeNameSeparators, StringSplitOptions.RemoveEmptyEntries), NodaTimeTypes.Contains);

    /// <summary>
    /// Whether a schema-required property needs the C# <c>required</c> modifier to satisfy
    /// nullable reference analysis.
    /// </summary>
    /// <remarks>
    /// A required value type (<c>double</c>, <c>long</c>, <c>bool</c>, an enum, a NodaTime value
    /// type such as <c>LocalDate</c>, or a mapped <c>struct</c> model such as <c>Agg</c>) already
    /// has a non-null default and needs nothing. A required reference type (<c>string</c>, an
    /// array, or another mapped <c>class</c> model) does not: the compiler-synthesized constructor
    /// exits without assigning it, which is CS8618 under this repository's warnings-as-errors
    /// build. The schema calling the field required is the fact being encoded -- <c>required</c>
    /// states it honestly, rather than an initializer such as <c>= null!</c> that pretends a value
    /// exists before one is read, or a nullable annotation that pretends the field might be absent
    /// when the schema says it never is. Reference-ness is read from the resolved type string
    /// alone (ends with <c>[]</c>, equals <c>string</c>, or names another non-<c>struct</c> model
    /// in the map), so the check is order-independent and rule 6 holds.
    /// </remarks>
    /// <param name="required">Whether the schema declares the property required.</param>
    /// <param name="type">The property's resolved C# type, nullable annotation included.</param>
    /// <returns><see langword="true"/> when the property needs the <c>required</c> modifier.</returns>
    private bool NeedsRequiredModifier(bool required, string type) =>
        required
        && !type.EndsWith('?')
        && (type == "string"
            || type.EndsWith("[]", StringComparison.Ordinal)
            || map.Models.Exists(m => m.Name == type && m.Kind != "struct"));

    private static void EmitGuards(CodeWriter writer, List<Argument> arguments)
    {
        foreach (Argument argument in arguments.Where(a => a is { Required: true, CSharpType: "string" }))
        {
            writer.Line($"ArgumentException.ThrowIfNullOrWhiteSpace({argument.Identifier});");
        }
    }

    private static void EmitParameterDocs(CodeWriter writer, List<Argument> arguments, string cancellationDescription)
    {
        foreach (Argument argument in arguments)
        {
            writer.Doc("param", argument.Description, $"name=\"{argument.Identifier}\"");
        }

        writer.Doc("param", cancellationDescription, "name=\"cancellationToken\"");
    }

    private static void EmitPath(CodeWriter writer, string path, List<Argument> arguments)
    {
        StringBuilder literal = new();
        int index = 0;

        while (index < path.Length)
        {
            if (path[index] != '{')
            {
                literal.Append(path[index++]);
                continue;
            }

            int close = path.IndexOf('}', index);
            string name = path[(index + 1)..close];
            index = close + 1;

            if (literal.Length > 0)
            {
                writer.Line($"builder.AppendPathLiteral(\"{literal}\");");
                literal.Clear();
            }

            Argument argument = arguments.First(a => a.WireName == name);
            writer.Line($"builder.{argument.PathAppendMethod}({argument.PathExpression});");
        }

        if (literal.Length > 0)
        {
            writer.Line($"builder.AppendPathLiteral(\"{literal}\");");
        }

        writer.Line();
    }

    private string EmitJsonContext()
    {
        CodeWriter writer = new();
        writer.Line(Header);
        writer.Line();
        writer.Line("using System.Text.Json.Serialization;");
        writer.Line("using MassiveDotNet.Serialization;");
        writer.Line();
        writer.Line("namespace MassiveDotNet.Rest.Serialization;");
        writer.Line();
        writer.Doc("summary", "Source-generated serialization metadata for every REST response envelope. Using a context rather than reflection keeps the SDK Native AOT compatible.");
        writer.Doc("remarks", "Calendar dates are read by <see cref=\"LocalDateJsonConverter\"/>, registered here once so no model property needs its own attribute.", preserveMarkup: true);
        writer.Line("[JsonSourceGenerationOptions(Converters = new[] { typeof(LocalDateJsonConverter) })]");

        foreach (MapEndpoint endpoint in map.Endpoints)
        {
            writer.Line($"[JsonSerializable(typeof({EnvelopeName(endpoint)}))]");
        }

        writer.Line("internal sealed partial class MassiveRestJsonContext : JsonSerializerContext;");

        return writer.ToString();
    }

    /// <summary>Wraps a parameter list one-per-line so long signatures stay readable.</summary>
    private static List<string> Signature(string prefix, IReadOnlyList<string> parameters)
    {
        List<string> lines = [$"{prefix}("];

        for (int i = 0; i < parameters.Count; i++)
        {
            string separator = i == parameters.Count - 1 ? ")" : ",";
            lines.Add($"    {parameters[i]}{separator}");
        }

        return lines;
    }

    private static string EnvelopeName(MapEndpoint endpoint) => $"{Naming.Pascal(endpoint.OperationId)}Response";

    private static string Summary(SpecOperation operation) =>
        operation.Operation.TryGetProperty("summary", out JsonElement summary)
            ? summary.GetString() ?? operation.OperationId
            : operation.OperationId;

    /// <summary>
    /// Appends a clause to a sentence so the result reads as one sentence, whether or not the
    /// source prose already ended in terminal punctuation.
    /// </summary>
    private static string? AppendClause(string? sentence, string clause) =>
        string.IsNullOrWhiteSpace(sentence)
            ? null
            : $"{sentence.TrimEnd().TrimEnd('.', '!', '?')}, {clause}";

    private static string DefaultPropertyType(SpecProperty property)
    {
        string type = TypeBinding.FromSchema(property.Schema);
        return property.Required || type == "string" ? Nullable(type, property.Required) : $"{type}?";
    }

    private static string NullableEnvelopeType(SpecProperty property)
    {
        string type = TypeBinding.FromSchema(property.Schema);
        return type == "string" ? "string?" : $"{type}?";
    }

    private static string Nullable(string type, bool required) =>
        required ? type : $"{type}?";
}
